---
dist: trusty
language: ruby
cache: bundler
before_install:
  - bundle -v
  - rm -f Gemfile.lock
  - gem update --system $RUBYGEMS_VERSION
  - gem --version
  - bundle -v
script:
  - 'bundle exec rake $CHECK'
bundler_args: --without system_tests
rvm:
  - 2.5.3
env:
  global:
    - SHELLCHECK_OPTS="-e SC1117"
stages:
  - static
  - spec
  - acceptance
  -
    if: tag =~ ^v\d
    name: deploy
matrix:
  fast_finish: true
  include:
    -
      env: CHECK="check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop syntax lint metadata_lint"
      stage: static
    -
      env: DEPLOY_TO_FORGE=yes
      stage: deploy
    -
      env: CHECK="shellcheck tasknames"
      stage: static
    -
      bundler_args: 
      dist: trusty
      env: ["PLATFORMS=deb_puppet5", "PROVISION_LIST=litmus_deb", "PUPPET_VERSION=puppet5"]
      rvm: 2.5.1
      script: ["bundle exec rake \"litmus:provision_list[${PROVISION_LIST}]\"", "bundle exec bolt command run 'apt-get install wget -y' --inventoryfile inventory.yaml --nodes='localhost*'", "bundle exec rake \"litmus:install_agent[${PUPPET_VERSION}]\"", "bundle exec rake litmus:install_module", "bundle exec rake litmus:acceptance:parallel"]
      services: docker
      stage: acceptance
      sudo: required
    -
      bundler_args: 
      dist: trusty
      env: ["PLATFORMS=deb_puppet6", "PROVISION_LIST=litmus_deb", "PUPPET_VERSION=puppet6"]
      rvm: 2.5.1
      script: ["bundle exec rake \"litmus:provision_list[${PROVISION_LIST}]\"", "bundle exec bolt command run 'apt-get install wget -y' --inventoryfile inventory.yaml --nodes='localhost*'", "bundle exec rake \"litmus:install_agent[${PUPPET_VERSION}]\"", "bundle exec rake litmus:install_module", "bundle exec rake litmus:acceptance:parallel"]
      services: docker
      stage: acceptance
      sudo: required
    -
      bundler_args: 
      dist: trusty
      env: ["PLATFORMS=el_puppet5", "PROVISION_LIST=litmus_el", "PUPPET_VERSION=puppet5"]
      rvm: 2.5.1
      script: ["bundle exec rake \"litmus:provision_list[${PROVISION_LIST}]\"", "bundle exec rake \"litmus:install_agent[${PUPPET_VERSION}]\"", "bundle exec rake litmus:install_module", "bundle exec rake litmus:acceptance:parallel"]
      services: docker
      stage: acceptance
      sudo: required
    -
      bundler_args: 
      dist: trusty
      env: ["PLATFORMS=el_puppet6", "PROVISION_LIST=litmus_el", "PUPPET_VERSION=puppet6"]
      rvm: 2.5.1
      script: ["bundle exec rake \"litmus:provision_list[${PROVISION_LIST}]\"", "bundle exec rake \"litmus:install_agent[${PUPPET_VERSION}]\"", "bundle exec rake litmus:install_module", "bundle exec rake litmus:acceptance:parallel"]
      services: docker
      stage: acceptance
      sudo: required
branches:
  only:
    - master
    - /^v\d/
    - /.*/
notifications:
  email: false
deploy:
  provider: puppetforge
  user: puppetlabs
  password:
    secure: "secure string to be inserted here"
  on:
    tags: true
    all_branches: true
    condition: "$DEPLOY_TO_FORGE = yes"
